# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range
minecraft_version_range=[1.21.1,1.21.2)
# The NeoForge version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.234
# The NeoForge version range
neo_version_range=[21.1,)
# The loader version range (FML)
loader_version_range=[4,)


## Mod Properties

# 模组独一无二的标识符。 必须符合正则 [a-z][a-z0-9_]{1,63} 。
mod_id=jsonmore
# 显示名称
mod_name=Json More
# 模组的许可证
mod_license=MIT
# 模组版本
mod_version=1.2.6
# 模组的分组 ID
mod_group_id=qikahome.jsonmore
# 模组的作者
mod_authors=Qikahome
# 模组的描述
mod_description=More things in JSON sauce.


# 前置模组的版本信息
json_things_version=0.13.7
json_things_range=[0.13.7,)
# JEI
jei_version=19.21.1.307
jei_range=[19.21.0,)
# Create
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
# CyclopsCore
cyclopscore_version=1.19.11
cyclopscore_range=[1.19.11,)
# Anvil MusBox
anvil_musbox_version=1.1.2
anvil_musbox_range=[1.1.0,)
# 暮色森林（Twilight Forest）
twilight_forest_version=4.6.2780
twilight_forest_range=[4.6.2780,)
